arb-dir: lib/src/localization/arb
template-arb-file: app_en.arb
output-dir: lib/src/localization/generated
output-localization-file: ehwplus_app_localizations.dart
output-class: EhwplusAppLocalizations
untranslated-messages-file: untranslated_messages.json