arb-dir: lib/src/localization/arb
template-arb-file: app_en.arb
output-dir: lib/src/localization/generated
output-localization-file: ehw_localizations.dart
output-class: EhwLocalizations
untranslated-messages-file: untranslated_messages.json