enum LanguageIconType {
  langAce('ace', 'Acehnese', 'Basa Acèh', '🇮🇩'),
  langAf('af', 'Afrikaans', 'Afrikaans', '🇿🇦'),
  langAn('an', 'Aragonese', 'Aragonés', 'A'),
  langAr('ar', 'Arabic', 'اَلْعَرَبِيَّةُ', 'ع'),
  langAs('as', 'Assamese', 'অসমীয়া', '🇮🇳'),
  langAy('ay', 'Aymara', 'Aymar aru', '▦'),
  langAz('az', 'Azerbaijani', 'Azərbaycanca', '🇦🇿'),
  langBa('ba', 'Bashkir', 'Башҡортса', 'Б'),
  langBe('be', 'Belarusian', 'Беларуская', '🇧🇾'),
  langBg('bg', 'Bulgarian', 'Български', '🇧🇬'),
  langBho('bho', 'Bhojpuri', 'भोजपुरी', '🇮🇳'),
  langBn('bn', 'Bengali', 'বাংলা', '🇧🇩'),
  langBr('br', 'Breton', 'Brezhoneg', 'B'),
  langBs('bs', 'Bosnian', 'Босански', '🇧🇦'),
  langCa('ca', 'Catalan', 'Català', 'C'),
  langCeb('ceb', 'Cebuano', 'Cebuano', '🇵🇭'),
  langCkb('ckb', 'Kurdish (Sorani)', 'کوردیی ناوەندی', '☀'),
  langCz('cs', 'Czech', 'Čeština', '🇨🇿'),
  langCy('cy', 'Welsh', 'Cymraeg', '🏴'),
  langDa('da', 'Danish', 'Dansk', '🇩🇰'),
  langDe('de', 'German', 'Deutsch', '🇩🇪'),
  langGr('el', 'Greek', 'Νέα Ελληνικά', '🇬🇷'),
  langEn('en', 'English', 'English', '🇬🇧'),
  langEo('eo', 'Esperanto', 'Esperanto', '★'),
  langEs('es', 'Spanish', 'Español', '🇪🇸'),
  langEt('et', 'Estonian', 'Eesti keel', '🇪🇪'),
  langEu('eu', 'Basque', 'Euskara', 'E'),
  langFa('fa', 'Persian', 'فارسی', '🇮🇷'),
  langFi('fi', 'Finnish', 'Suomi', '🇫🇮'),
  langFr('fr', 'French', 'Français', '🇫🇷'),
  langGa('ga', 'Irish', 'Gaeilge', '🇮🇪'),
  langGl('gl', 'Galician', 'Galego', 'G'),
  langGn('gn', 'Guarani', "Avañe'ẽ", '🇵🇾'),
  langGom('gom', 'Konkani', 'कोंकणी', '🇮🇳'),
  langGu('gu', 'Gujarati', 'ગુજરાતી', '🇮🇳'),
  langHa('ha', 'Hausa', 'Hausa', '🇳🇬'),
  langHe('he', 'Hebrew', 'עברית', '🇮🇱'),
  langHi('hi', 'Hindi', 'हिन्दी', '🇮🇳'),
  langHr('hr', 'Croatian', 'Hrvatski', '🇭🇷'),
  langHt('ht', 'Haitian Creole', 'Kreyòl ayisyen', '🇭🇹'),
  langHu('hu', 'Hungarian', 'Magyar', '🇭🇺'),
  langHy('hy', 'Armenian', 'Հայերեն', '🇦🇲'),
  langId('id', 'Indonesian', 'Bahasa Indonesia', '🇮🇩'),
  langIg('ig', 'Igbo', 'Igbo', '🇳🇬'),
  langIs('is', 'Icelandic', 'Íslenska', '🇮🇸'),
  langIt('it', 'Italian', 'Italiano', '🇮🇹'),
  langJa('ja', 'Japanese', '日本語', '🇯🇵'),
  langJv('jv', 'Javanese', 'Basa Jawa', '🇮🇩'),
  langKa('ka', 'Georgian', 'ქართული', '🇬🇪'),
  langKk('kk', 'Kazakh', 'Қазақша', '🇰🇿'),
  langKmr('kmr', 'Kurdish (Kurmanji)', 'Kurmancî', '☀'),
  langKo('ko', 'Korean', '한국어', '🇰🇷'),
  langKy('ky', 'Kyrgyz', 'Кыргызча', '🇰🇬'),
  langLa('la', 'Latin', 'Latina', '🇻🇦'),
  langLb('lb', 'Luxembourgish', 'Lëtzebuergesch', '🇱🇺'),
  langLmo('lmo', 'Lombard', 'Lombard', 'L'),
  langLn('ln', 'Lingala', 'Lingála', '🇨🇩'),
  langLt('lt', 'Lithuanian', 'Lietuvių', '🇱🇹'),
  langLv('lv', 'Latvian', 'Latviešu', '🇱🇻'),
  langMai('mai', 'Maithili', 'मैथिली', '🇮🇳'),
  langMg('mg', 'Malagasy', 'Malagasy', '🇲🇬'),
  langMi('mi', 'Maori', 'Māori', '🇳🇿'),
  langMk('mk', 'Macedonian', 'Македонски', '🇲🇰'),
  langMl('ml', 'Malayalam', 'മലയാളം', 'മ'),
  langMn('mn', 'Mongolian', 'Монгол', '🇲🇳'),
  langMr('mr', 'Marathi', 'मराठी', '🇮🇳'),
  langMs('ms', 'Malay', 'Bahasa Melayu', '🇲🇾'),
  langMt('mt', 'Maltese', 'Malti', '🇲🇹'),
  langMy('my', 'Burmese', 'Mrãmācā', '🇲🇲'),
  langNo('nb', 'Norwegian Bokmål', 'Norsk', '🇳🇴'),
  langNe('ne', 'Nepali', 'नेपाली', '🇳🇵'),
  langNl('nl', 'Dutch', 'Nederlands', '🇳🇱'),
  langOc('oc', 'Occitan', 'Occitan', 'O'),
  langOm('om', 'Oromo', 'Afaan Oromoo', '🇪🇹'),
  langPa('pa', 'Punjabi', 'ਪੰਜਾਬੀ', '🇮🇳'),
  langPag('pag', 'Pangasinan', 'Pangasinan', '🇵🇭'),
  langPam('pam', 'Kapampangan', 'Kapampangan', '🇵🇭'),
  langPl('pl', 'Polish', 'Polski', '🇵🇱'),
  langPrs('prs', 'Dari', 'دری', '🇦🇫'),
  langPs('ps', 'Pashto', 'پښتو', '🇦🇫'),
  langPt('pt', 'Portuguese', 'Português', '🇵🇹'),
  langQu('qu', 'Quechua', 'Runasimi', '▦'),
  langRo('ro', 'Romanian', 'Română', '🇷🇴'),
  langRu('ru', 'Russian', 'Русский язык', '🇷🇺'),
  langSa('sa', 'Sanskrit', 'संस्कृतम्', '🇮🇳'),
  langScn('scn', 'Sicilian', 'Sicilianu', 'S'),
  langSk('sk', 'Slovak', 'Slovenčina', '🇸🇰'),
  langSl('sl', 'Slovenian', 'Slovenščina', '🇸🇮'),
  langSq('sq', 'Albanian', 'Shqip', '🇦🇱'),
  langSr('sr', 'Serbian', 'Српски', '🇷🇸'),
  langSt('st', 'Sesotho', 'Sesotho', '🇱🇸'),
  langSu('su', 'Sundanese', 'Basa Sunda', '🇮🇩'),
  langSv('sv', 'Swedish', 'Svenska', '🇸🇪'),
  langSw('sw', 'Swahili', 'Kiswahili', '🇰🇪'),
  langTa('ta', 'Tamil', 'தமிழ்', '🇮🇳'),
  langTe('te', 'Telugu', 'తెలుగు', '🇮🇳'),
  langTg('tg', 'Tajik', 'Тоҷикӣ', '🇹🇯'),
  langTh('th', 'Thai', 'ภาษาไทย', '🇹🇭'),
  langTk('tk', 'Turkmen', 'Türkmençe', '🇹🇲'),
  langTl('tl', 'Tagalog', 'Tagalog', '🇵🇭'),
  langTn('tn', 'Tswana', 'Setswana', '🇧🇼'),
  langTr('tr', 'Turkish', 'Türkçe', '🇹🇷'),
  langTs('ts', 'Tsonga', 'XiTsonga', '🇿🇦'),
  langTt('tt', 'Tatar', 'Татарча', '🇷🇺'),
  langUk('uk', 'Ukrainian', 'Українська', '🇺🇦'),
  langUr('ur', 'Urdu', 'اردو', '🇵🇰'),
  langUz('uz', 'Uzbek', 'Oʻzbekcha', '🇺🇿'),
  langVi('vi', 'Vietnamese', 'tiếng Việt', '🇻🇳'),
  langWo('wo', 'Wolof', 'Wolof', '🇸🇳'),
  langXh('xh', 'Xhosa', 'isiXhosa', '🇿🇦'),
  langYi('yi', 'Yiddish', 'ייִדיש', 'יי'),
  langYue('yue', 'Cantonese', '粵語', '🇭🇰'),
  langZh('zh', 'Chinese', '中文', '🇨🇳'),
  langZu('zu', 'Zulu', 'isiZulu', '🇿🇦');

  const LanguageIconType(this.fileName, this.isoName, this.endonym, this.icon);

  final String fileName;

  final String endonym;

  final String isoName;

  final String icon;

  static LanguageIconType fromStringValue(String value) {
    return LanguageIconType.values.firstWhere((enumId) => enumId.fileName == value);
  }
}
