arb-dir: lib/src/localization/arb
template-arb-file: app_de.arb
output-dir: lib/src/localization/generated
output-localization-file: arb_editor_localizations.dart
output-class: ArbEditorLocalizations
untranslated-messages-file: untranslated_messages.json
